name: Run app.py
on:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 1. Get the user's code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Python (The environment)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run app.py to see if it crashes
      # If this crashes, the step fails, and GitHub reports "Failure"
      - name: Run Main File
        run: timeout 10s python app.py || [ $? -eq 124 ]